import type { Offer, Transaction, LiveActivityEvent, CompanyOffer } from "../types/types";


export const OFFERS: Offer[] = [
  {
    id: "off_disc_01",
    code: "SAVE10",
    type: "DISCOUNT",
    benefitAmount: 10,
    minPaymentAmount: 50,
    remainingBudget: 4_250,
    totalBudget: 10_000,
    status: "ACTIVE",
    description: "10% off on payments over $50",
  },
  {
    id: "off_disc_02",
    code: "FLAT25",
    type: "DISCOUNT",
    benefitAmount: 25,
    minPaymentAmount: 200,
    remainingBudget: 875,
    totalBudget: 5_000,
    status: "ACTIVE",
    description: "$25 flat discount on payments over $200",
  },
  {
    id: "off_cash_01",
    code: "CASH5PCT",
    type: "CASHBACK",
    benefitAmount: 5,
    minPaymentAmount: 100,
    remainingBudget: 12_000,
    totalBudget: 20_000,
    status: "ACTIVE",
    description: "5% cashback on payments over $100",
  },
  {
    id: "off_cash_02",
    code: "CB15PLUS",
    type: "CASHBACK",
    benefitAmount: 15,
    minPaymentAmount: 500,
    remainingBudget: 320,
    totalBudget: 8_000,
    status: "ACTIVE",
    description: "$15 cashback on payments over $500",
  },
];

const now = new Date();
const ago = (minutes: number) => new Date(now.getTime() - minutes * 60_000);

export const SENDER_TRANSACTIONS: Transaction[] = [
  { id: "tx_001", time: ago(2), counterparty: "Jordan Blake", amount: 340.00, currency: "INR", status: "COMPLETED", direction: "out" },
  { id: "tx_002", time: ago(18), counterparty: "Sam Rivera", amount: 1_200.50, currency: "INR", status: "COMPLETED", direction: "out" },
  { id: "tx_003", time: ago(45), counterparty: "Jordan Blake", amount: 75.00, currency: "INR", status: "FAILED", direction: "out" },
  { id: "tx_004", time: ago(90), counterparty: "Sam Rivera", amount: 525.00, currency: "INR", status: "COMPLETED", direction: "out" },
  { id: "tx_005", time: ago(180), counterparty: "Jordan Blake", amount: 89.99, currency: "INR", status: "COMPLETED", direction: "out" },
  { id: "tx_006", time: ago(240), counterparty: "Sam Rivera", amount: 2_100.00, currency: "INR", status: "COMPLETED", direction: "out" },
  { id: "tx_007", time: ago(360), counterparty: "Jordan Blake", amount: 450.00, currency: "INR", status: "PENDING", direction: "out" },
  { id: "tx_008", time: ago(480), counterparty: "Sam Rivera", amount: 310.25, currency: "INR", status: "COMPLETED", direction: "out" },
  { id: "tx_009", time: ago(600), counterparty: "Jordan Blake", amount: 65.00, currency: "INR", status: "COMPLETED", direction: "out" },
  { id: "tx_010", time: ago(720), counterparty: "Sam Rivera", amount: 980.00, currency: "INR", status: "COMPLETED", direction: "out" },
  { id: "tx_011", time: ago(900), counterparty: "Jordan Blake", amount: 145.50, currency: "INR", status: "COMPLETED", direction: "out" },
  { id: "tx_012", time: ago(1080), counterparty: "Sam Rivera", amount: 3_500.00, currency: "INR", status: "COMPLETED", direction: "out" },
];

export const RECEIVER_TRANSACTIONS: Transaction[] = [
  { id: "rx_001", time: ago(2), counterparty: "Alex Chen", amount: 340.00, currency: "INR", status: "COMPLETED", direction: "in" },
  { id: "rx_002", time: ago(25), counterparty: "External", amount: 820.00, currency: "INR", status: "COMPLETED", direction: "in" },
  { id: "rx_003", time: ago(55), counterparty: "Alex Chen", amount: 1_200.50, currency: "INR", status: "COMPLETED", direction: "in" },
  { id: "rx_004", time: ago(120), counterparty: "External", amount: 60.00, currency: "INR", status: "COMPLETED", direction: "in" },
  { id: "rx_005", time: ago(200), counterparty: "Alex Chen", amount: 525.00, currency: "INR", status: "COMPLETED", direction: "in" },
  { id: "rx_006", time: ago(280), counterparty: "External", amount: 1_450.00, currency: "INR", status: "COMPLETED", direction: "in" },
  { id: "rx_007", time: ago(400), counterparty: "Alex Chen", amount: 89.99, currency: "INR", status: "COMPLETED", direction: "in" },
  { id: "rx_008", time: ago(520), counterparty: "External", amount: 230.00, currency: "INR", status: "FAILED", direction: "in" },
  { id: "rx_009", time: ago(640), counterparty: "Alex Chen", amount: 310.25, currency: "INR", status: "COMPLETED", direction: "in" },
  { id: "rx_010", time: ago(760), counterparty: "External", amount: 750.00, currency: "INR", status: "COMPLETED", direction: "in" },
  { id: "rx_011", time: ago(900), counterparty: "Alex Chen", amount: 65.00, currency: "INR", status: "COMPLETED", direction: "in" },
  { id: "rx_012", time: ago(1100), counterparty: "External", amount: 1_800.00, currency: "INR", status: "COMPLETED", direction: "in" },
];

export const INITIAL_LIVE_ACTIVITY: LiveActivityEvent[] = [
  {
    id: "act_001",
    type: "payment_received",
    amount: 340.00,
    currency: "INR",
    from: "Alex Chen",
    message: "Payment received from Alex Chen",
    timestamp: ago(2),
  },
  {
    id: "act_002",
    type: "cashback_received",
    amount: 17.00,
    currency: "INR",
    message: "Cashback credited from CASH5PCT offer",
    timestamp: ago(18),
  },
  {
    id: "act_003",
    type: "offer_redeemed",
    message: "Offer SAVE10 redeemed successfully",
    timestamp: ago(45),
  },
  {
    id: "act_004",
    type: "payment_received",
    amount: 1_200.50,
    currency: "INR",
    from: "Alex Chen",
    message: "Payment received from Alex Chen",
    timestamp: ago(90),
  },
  {
    id: "act_005",
    type: "refund_received",
    amount: 75.00,
    currency: "INR",
    message: "Refund processed for tx_003",
    timestamp: ago(150),
  },
];

export const COMPANY_OFFERS: CompanyOffer[] = [
  {
    id: "coff_01",
    code: "SAVE10",
    type: "DISCOUNT",
    benefitAmount: 10,
    isPercentage: true,
    maxBenefit: 500,
    minPaymentAmount: 50,
    maxPaymentAmount: null,
    maxRedemptions: 10000,
    perUserLimit: 3,
    startTime: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
    endTime: new Date(now.getTime() + 21 * 24 * 60 * 60 * 1000),
    promotionPoolName: "SWIGGY_SAVE10_POOL",
    initialBudget: 10_000,
    remainingBudget: 4_250,
    totalRedemptions: 576,
    conversionRate: 68.4,
    status: "ACTIVE",
    fundingStatus: "FUNDED",
    createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    id: "coff_02",
    code: "FLAT25",
    type: "DISCOUNT",
    benefitAmount: 25,
    isPercentage: false,
    maxBenefit: 25,
    minPaymentAmount: 200,
    maxPaymentAmount: null,
    maxRedemptions: 2000,
    perUserLimit: 1,
    startTime: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
    endTime: new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000),
    promotionPoolName: "SWIGGY_FLAT25_POOL",
    initialBudget: 5_000,
    remainingBudget: 875,
    totalRedemptions: 165,
    conversionRate: 41.2,
    status: "ACTIVE",
    fundingStatus: "FUNDED",
    createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: "coff_03",
    code: "CASH5PCT",
    type: "CASHBACK",
    benefitAmount: 5,
    isPercentage: true,
    maxBenefit: 200,
    minPaymentAmount: 100,
    maxPaymentAmount: null,
    maxRedemptions: 50000,
    perUserLimit: 10,
    startTime: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000),
    endTime: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000),
    promotionPoolName: "SWIGGY_CASH5PCT_POOL",
    initialBudget: 20_000,
    remainingBudget: 12_000,
    totalRedemptions: 2_188,
    conversionRate: 79.1,
    status: "ACTIVE",
    fundingStatus: "FUNDED",
    createdAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000),
  },
  {
    id: "coff_04",
    code: "CB15PLUS",
    type: "CASHBACK",
    benefitAmount: 15,
    isPercentage: false,
    maxBenefit: 15,
    minPaymentAmount: 500,
    maxPaymentAmount: null,
    maxRedemptions: 1000,
    perUserLimit: 2,
    startTime: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
    endTime: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000),
    promotionPoolName: "SWIGGY_CB15PLUS_POOL",
    initialBudget: 8_000,
    remainingBudget: 320,
    totalRedemptions: 652,
    conversionRate: 33.8,
    status: "ACTIVE",
    fundingStatus: "FUNDED",
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
  },
];

export function generateId(prefix: string): string {
  return `${prefix}_${Math.random().toString(36).slice(2, 10).toUpperCase()}`;
}

export function generateIdempotencyKey(): string {
  return `idem_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}
